#!/bin/sh

if [ ! -x /usr/local/bin/jo ]; then
	echo "no such /usr/local/bin/jo, please install textproc/jo"
fi

/usr/local/bin/jo -p flavor=$( jo -a $( env NOCOLOR=1 /usr/local/bin/cbsd vm-packages display=name,pkg_vm_cpus,pkg_vm_ram,pkg_vm_disk header=0 | while read _name _cpus _ram _dsk; do
	echo -n "$( /usr/local/bin/jo name=${_name} cpus=${_cpus} ram=${_ram} imgsize=${_dsk} ) "
done ))
